[package]
name = "antigfw-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.60"
nanorpc = "0.1.12"
serde_json = "1.0.91"
thiserror = "1.0.38"
